### ISSUE TITLE
setup login page

### ISSUE THREAD

**Issue by katsanevakis** [swiftss-org/registry-api#9]

**Comment by dkoutsonikolis** [comment]
Regarding the Sign In screens, we have created an admin user(username: tmh_registry_admin, password: r3g1stry_p@ss) which you can use in order to login to the backend Staging admin page(https://tmh-registry-api-staging.herokuapp.com/admin). There you can also add new users.

Once a user is created through the admin page, then the Frontend can use the `/sign-in` endpoint in order to get the authentication token. The only change is that we use the username instead of the email, is this ok @katsanevakis ?

Regarding the Forgot Password page, we have not implemented anything yet. Password resets can happen manually from the admin page though. I believe we can skip this page for now, in order to concentrate on core functionality. Any comments about that @katsanevakis?

**Comment by katsanevakis** [comment]
@dkoutsonikolis  I cant login with the above credentials

using usernames instead of emails is ok

forgot passwords functionality is not part of the scope at this stage

**Comment by dkoutsonikolis** [comment]
@katsanevakis Try again, it should work now! Thanks for the replies!
